"use client";
import { Container, Paper } from "@mui/material";
import Header from "../containers/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { NavermapsProvider } from "react-naver-maps";
import Head from "next/head";

// if (
//   process.env.NODE_ENV === "development" ||
//   process.env.NODE_ENV === "production"
// ) {
//   // for mock api
//   import("../_mocks");
// }

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Episode",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <Head>
        <meta http-equiv="Cache-Control" content="no-cache" />
      </Head>
      <body
        className={inter.className}
        style={{ display: "flex", width: "100%" }}
      >
        <NavermapsProvider ncpClientId={process.env.MAP_API_KEY || ""}>
          <Container
            sx={{
              position: "relative",
              display: "flex",
              maxWidth: 600,
              justifyContent: "center",
              padding: 0,
            }}
          >
            <Paper
              sx={{
                padding: 0,
                position: "relative",
                display: "flex",
                flexDirection: "column",
                width: "100%",
              }}
            >
              <Header />
              {children}
            </Paper>
          </Container>
        </NavermapsProvider>
      </body>
    </html>
  );
}
